### PR TITLE
Fixed bug of missing avatar_id

### PR DESCRIPTION
**Pull request by matgrube**

### CODE REVIEW

**Review by s-kakol — APPROVED** [review]
Good enough, imho prefered way would be checking if the avatar has been found in the DB and throwing an exception instead, like so:
`if (!avatar) throw new HttpException(``Avatar with id:${id} not found``, HttpStatus.NOT_FOUND);`

But this works as well.

**Comment by matgrube** [comment]
> Good enough, imho prefered way would be checking if the avatar has been found in the DB and throwing an exception instead, like so: `` if (!avatar) throw new HttpException(``Avatar with id:${id} not found``, HttpStatus.NOT_FOUND); ``
> 
> But this works as well.

I don't think you understand the issue.
No matter if the avatar is inside the database we are trying to add an instance of a user to the database with `avatar_id` being null. We will have the column with JUST nulls. 
If the avatar_id is present in images table, then the `avatar` column will get properly populated, but the `avatar_id` will stay null for all of entities. I guess. 
Exception is a totally different thing.

**Comment by s-kakol** [comment]
> > Good enough, imho prefered way would be checking if the avatar has been found in the DB and throwing an exception instead, like so: ` if (!avatar) throw new HttpException(`Avatar with id:${id} not found`, HttpStatus.NOT_FOUND); `
> > But this works as well.
> 
> I don't think you understand the issue. No matter if the avatar is inside the database we are trying to add an instance of a user to the database with `avatar_id` being null. We will have the column with JUST nulls. If the avatar_id is present in images table, then the `avatar` column will get properly populated, but the `avatar_id` will stay null for all of entities. I guess. Exception is a totally different thing.

But, why?

**Comment by matgrube** [comment]
> > > Good enough, imho prefered way would be checking if the avatar has been found in the DB and throwing an exception instead, like so: ` if (!avatar) throw new HttpException(`Avatar with id:${id} not found`, HttpStatus.NOT_FOUND); `
> > > But this works as well.
> > 
> > 
> > I don't think you understand the issue. No matter if the avatar is inside the database we are trying to add an instance of a user to the database with `avatar_id` being null. We will have the column with JUST nulls. If the avatar_id is present in images table, then the `avatar` column will get properly populated, but the `avatar_id` will stay null for all of entities. I guess. Exception is a totally different thing.
> 
> But, why?

Because we're creating a new user in userRepository with `...userDetails` (destructured from dto, so that it does not contain `avatar_id`), `avatar`, `experience` and `settings`.

**Comment by matgrube** [comment]
Explained by @s-kakol - misunderstanding of error message. Closing PR.

**Pull request closed without merging**
